### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by tm545** [tm545/Personal#2]
### **Sample Part**
- [ ] No instanced parts
- [ ] Features are named to describe their function
- [ ] Parts are named descriptively (nothing named part 1)
- [ ] Only use configurations for variables that are owned by the part you're work on
- [ ] Bring in variables from children parts using super derive and add in that part's name as a prefix
- [ ] Name configurations and variables to describe their function
- [ ] Minimize the amount of features within a part studio
- [ ] Placed in correct folder within Aguaclara plant project
- [ ] Features are placed within folders to organize feature list
- [ ] Ensure that your part works even after configurations are shifted around
- [ ] Your part studio is understandable to someone new on the project
